# Generated by Django 5.1.7 on 2025-06-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crucenoTrip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='direccion',
        ),
    ]
